drop table if exists entries;
create table entries (
    id          integer      generated by default as identity(start with 1, increment by 1) primary key,
    name        varchar(255) not null   unique,
    shortname   varchar(255) not null   unique
);

create unique index name_shortname_idx on entries (name, shortname);
